### ISSUE TITLE
Result levels are different or not all existing comparing to the help text

### ISSUE THREAD

**Issue by TBoonX** [AKSW/RDFUnit#113]
## Expected Behavior
That the four result levels named in the --help text are recognized.

## Actual Behavior
rlog and extended are not recognized: "Option --result-level defined but not recognised. Using 'aggregate' by default."

## Steps to Reproduce the Problem

  1. Run docker container: `docker run --rm -it -p 80:80 --entrypoint="" aksw/rdfunit /bin/bash`
  2. Execute RDFUnit with --result-level and rlog or extended as parameter value.

## Specifications

  - Version: https://hub.docker.com/r/aksw/rdfunit
  - Platform: Mac OS
  - Subsystem: docker engine

**Comment by jimkont** [comment]
If I remember correctly I had removed these options as deprecated in favor of `shacl-lite` (equivalent to rlog) and `shacl` (equivalent to extended).
these new formats provide the same level of detail and are also based on the SHACL vocabulary which makes them more compatible with other systems
