### ISSUE TITLE
Default cache ignores `-T 0` setting

### ISSUE THREAD

**Issue by cosletmihai** [AKSW/RDFUnit#119]
## Expected Behavior
Based on the wiki page here https://github.com/AKSW/RDFUnit/wiki/SPARQL-Endpoints#default-cache , setting `-T 0` should disable validation cashing for SPARQL endpoints.

## Actual Behavior
Cashing still happens no matter what value I set to `-T`.

## Steps to Reproduce the Problem
Run the validation of a SPARQL endpoint using the `jar` 

## Specifications

  - Version: `master` branch 
  - Platform: Centos 7 and Docker

This has both been run on a Centos 7 system and inside a Docker container with the same results previously mentioned.

Has there been a change in the CLI usage that has not been mentioned in the wiki?

**Comment by jimkont** [comment]
thanks for the report, I verified that the `-T 0` option was ignored and fixed it in master. For some reason, I didn't notice this issue when it was originally reported
