### ISSUE TITLE
RDFUnit Demo page: undefined prefix https

### ISSUE THREAD

**Issue by k00ni** [AKSW/RDFUnit#41]
I want to use the following URI for test data: https://raw.githubusercontent.com/GeoKnow/GeoQuality/master/GeoKnow-SpatialDQ/datacubes/NUTS/NUTS-metric1-6.ttl

Its a ttl-file located at Github. I selected at your RDFUnit demo page **http://rdfunit.aksw.org/demo/** the Data Selection setting **Direct Input**. After clicking to **Load** the following error appears:

> Error: Cannot read dump URI: http://rdfunit.aksw.org/CustomSource#0865b91b4e8bd1c8c885af0827b6587a15451fc6bc743ef8b66e5c32f86f6a80 Reason: [line: 1, col: 1 ] Undefined prefix: http

What am i doing wrong?

**Comment by k00ni** [comment]
Sorry for the overhasty issue, i had to choose **remote file** instead of **direct input**. My bad.

**Comment by jimkont** [comment]
you should change the option to `remote files` and use the URI or leave `direct input` but paste the RDF data in the textbox

**Comment by jimkont** [comment]
no worries :)
