### ISSUE TITLE
Resource Filtering

### ISSUE THREAD

**Issue by pepperbob** [AKSW/RDFUnit#50]
While writing input/drafts for #49 we encountered issues with writing Tests. Problem is that the Module `rdfunit-resources` is required but this won't work unless Maven copied certain resources from the `/configuration` folder to the appropriate package in `/rdfunit-resources/src/main/resources`.

To run Unit-Tests without the requirement to invoke Maven beforehand, specific resources should be maintained in the `rdfunit-resources` module directly instead of `/configuration`.

**Comment by pepperbob** [comment]
Just noticed the `data/tests` folder is part of the artifact of rdfunit-resources; is this how it's meant to be?

**Comment by jimkont** [comment]
On every re-build all patterns/generators and manual tests are copied to related java resources folders.
This was done to make it easier for people to locate specific files. e.g.
* `configuration/*` for patterns & generators or
* `data/tests/manual/*' for manual tests

This can be inconvenient a few times but didn't find a better alternative so far. Suggestions are of course welcome

**Comment by dhiller** [comment]
Wouldn't it be better if the files are found where they should reside, and the README documents where they are? This way you could just skip the copy-resources.

**Comment by jimkont** [comment]
No strong opinion so fine by me. See you already work on a PR on this, feel free to submit :)
