### ISSUE TITLE
JUnit integration - Lazy creation of input models

### ISSUE THREAD

**Issue by dhiller** [AKSW/RDFUnit#52]
ATM the input models are eagerly created, this could be deferred to directly before running the test case against the input model.

**Comment by pepperbob** [comment]
Currently, if only one of the `@TestInput`-methods throws an error (e.g. RDF is not parsable), we propagate an InitializationError which stops the entire Runner from executing any tests at all.

In case the `@TestInput`-method fails, the entire TestSuite should be marked as "skipped" - the error message should be shown though (objections?).
