### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by roland-c** [AKSW/RDFUnit#58]
When testing the build there is an error:
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing

Results :

Tests in error:
  PrefixNSServiceTest.initializationError » NoClassDefFound org/hamcrest/SelfDes...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

Please refer to /opt/rdfunit/rdfunit-commons/target/surefire-reports for the individual test results.
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8 seconds
[INFO] Finished at: Sat Jan 23 13:26:09 CET 2016
[INFO] Final Memory: 86M/1722M
[INFO] ------------------------------------------------------------------------

**Comment by jimkont** [comment]
Thanks for the report @roland-c 
the latest build is compiling fine: https://travis-ci.org/AKSW/RDFUnit
can you pull and test again?

**Comment by roland-c** [comment]
Not sure what the problem is but the error remains:

roland@kblod:/opt/rdfunit$ git pull
Already up-to-date.
roland@kblod:/opt/rdfunit$ mvn clean install
[INFO] Scanning for projects...
[INFO] Reactor build order: 
[INFO]   RDFUnit - Parent
[INFO]   RDFUnit - Commons
[INFO]   RDFUnit - IO
[INFO]   RDFUnit - Manual Tests
[INFO]   RDFUnit - Model
[INFO]   RDFUnit - Core
[INFO]   RDFUnit - Validate
[INFO]   RDFUnit - Examples
[INFO]   RDFUnit - JUnit Integration
[INFO]   RDFUnit - W3c DQV
[INFO] ------------------------------------------------------------------------
[INFO] Building RDFUnit - Parent
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] [enforcer:enforce {execution: default}]
[INFO] [site:attach-descriptor {execution: default-attach-descriptor}]
[INFO] [install:install {execution: default-install}]
[INFO] Installing /opt/rdfunit/pom.xml to /home/roland/.m2/repository/org/aksw/rdfunit/rdfunit-parent/0.7.21-SNAPSHOT/rdfunit-parent-0.7.21-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Building RDFUnit - Commons
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean {execution: default-clean}]
[INFO] Deleting file set: /opt/rdfunit/rdfunit-commons/target (included: [**], excluded: [])
[INFO] [enforcer:enforce {execution: default}]
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[WARNING] POM for 'junit:junit:pom:4.12:test' is invalid.

Its dependencies (if any) will NOT be available to the current build.
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /opt/rdfunit/rdfunit-commons/target/classes
[INFO] [resources:testResources {execution: default-testResources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/rdfunit/rdfunit-commons/src/test/resources
[INFO] [compiler:testCompile {execution: default-testCompile}]
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /opt/rdfunit/rdfunit-commons/target/test-classes
[INFO] [surefire:test {execution: default-test}]

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.aksw.rdfunit.services.PrefixNSServiceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.018 sec <<< FAILURE! - in org.aksw.rdfunit.services.PrefixNSServiceTest
initializationError(org.aksw.rdfunit.services.PrefixNSServiceTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing


Results :

Tests in error: 
  PrefixNSServiceTest.initializationError » NoClassDefFound org/hamcrest/SelfDes...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] There are test failures.

Please refer to /opt/rdfunit/rdfunit-commons/target/surefire-reports for the individual test results.
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8 seconds
[INFO] Finished at: Mon Jan 25 00:19:28 CET 2016
[INFO] Final Memory: 86M/1722M
[INFO] ------------------------------------------------------------------------

**Comment by jimkont** [comment]
Strange... Can you delete your ~/.m2 folder and retry?

**Comment by roland-c** [comment]
That did the trick, thanks Dimitris!

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------

**Comment by roland-c** [comment]
But the when I run ther is the next buikd error:

$ bin/rdfunit -d http://lod.kb.nl/nbc/ -e http://lod.kb.nl/sparql  -g http://lod.kb.nl/nbc/
[ERROR] BUILD ERROR

The log states:
10:22:15,625 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://www.w3.org/1999/02/22-rdf-syntax-ns#
10:22:15,626 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://example.com/c2#
10:22:15,628 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://example.com/p4#
10:22:15,628 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://example.com/p5#
10:22:15,628 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://example.com/p2#
10:22:15,629 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://example.com/p3#
10:22:15,629 WARN  NamespaceStatistics: Undefined namespace in LOV or schemaDecl.csv: http://example.com/p1#
10:22:43,937 ERROR DumpTestSource: Cannot read dump URI: non-resolvable-uri Reason: null

**Comment by jimkont** [comment]
can you pull and give another shot?

**Comment by roland-c** [comment]
Now that works, thanks man.
