### ISSUE TITLE
Preconditions failure

### ISSUE THREAD

**Issue by sandroacoelho** [AKSW/RDFUnit#63]
Hi,

I've found a small bug in TestExecutionImpl. It fails at [#L207](https://github.com/AKSW/RDFUnit/blob/939ae6e747859e422edfaa4b5c562ab68c01d8b6/rdfunit-core/src/main/java/org/aksw/rdfunit/tests/executors/monitors/SimpleTestExecutorMonitor.java#L207)  when the method testingFinished() is called. A value for ExecutionType is required for other methods that uses the same builder. 

Could you, please , give me a hand on it? 

Thank you in advance

**Comment by jimkont** [comment]
I found the bug too and fixed it yesterday (before my PR) but forgot to push and that it why the PR failed :)
https://github.com/AKSW/RDFUnit/commit/a5bd2f1b6135e41e567a7fbe4e27c128cb17fdab
