### ISSUE TITLE
Want to see the triple with S,P,O

### ISSUE THREAD

**Issue by kaka7537** [AKSW/RDFUnit#65]
![error case](https://cloud.githubusercontent.com/assets/7700725/14452009/6c02a5b0-00c6-11e6-84b8-fd5951f16e16.png)
In this screenshot, I can see some properties that occur errors. but I'd like to see the triple with S, P, O format that occur errors. For example, 
S1 http://dbpedia.org/ontology/influencedBy O1
S2 http://dbpedia.org/ontology/influencedBy O2
S3 http://dbpedia.org/ontology/influencedBy O3
S4 http://dbpedia.org/ontology/influencedBy O4 
It will show us 4 triples because 'http://dbpedia.org/ontology/influencedBy' property occurs 4 errors in this screenshot.
I tried to fix some code after clone this code on my local machine, but it is too big to fix.. I have no idea where to fix.. Would you give me some advice?
Thank you

**Comment by jimkont** [comment]
Hi, RDFUnit can return results in different formats, see [here](https://github.com/AKSW/RDFUnit/wiki/Results) for examples.
 by default the results are stored in the folder `./data/results` in `html`, you can request other (multiple) formats with `-o ttl,html,...`

Does this cover your question?

**Comment by jimkont** [comment]
in your case, if you want the whole triple you should use `-r extended` but note that this is not possible in all cases e.g. when something is missing.

**Comment by kaka7537** [comment]
Thank you for replying!
I added '-r extended' command. So I typed 'bin/rdfunit -d <MY_TTL_FILE> -r extended'. and the result is the picture below.
As you can see, it didn't show S, P, O.
![2](https://cloud.githubusercontent.com/assets/7700725/14490196/6ebce806-01ac-11e6-83c8-8706820de2ee.png)

**Comment by jimkont** [comment]
if you look at my first comment: https://github.com/AKSW/RDFUnit/issues/65#issuecomment-209308238 you can get the results in different formats
> by default the results are stored in the folder ./data/results in html, you can request other (multiple) formats with -o ttl,html,...

**Comment by kaka7537** [comment]
'-o ttl' command show me the triple with S,P,O format. but this isn't what I expected to see.
I want to see the exact triples in my TTL file that occur errors.
for example, if 'http://dbpedia.org/ontology/country' property occurs 1 error, the machine extract that triple in my TTL file. like, <http://ko.dbpedia.org/resource/테네시_주>	<http://dbpedia.org/ontology/country>	<http://ko.dbpedia.org/resource/미국>	.

**Comment by jimkont** [comment]
Does this solve your problem? You cannot always know all `s|p|o`, sometimes you know only `s` and other only `s|p`

e.g. for `minCount 1 for ex:prop` constraints violations you can only tell `s|p` not 'o'

**Comment by jimkont** [comment]
feel free to re-open if that solution does not cover your issue
