### ISSUE TITLE
Re-activate or document custom SPARQL query support

### ISSUE THREAD

**Issue by seebi** [AKSW/RDFUnit#66]
Dimitri, I know you work on SHACL but to have support for custom queries is an important feature and would ease up a lot here at eccenca. Let us talk how to re-activate or use that please :-)

**Comment by der-bruemmer** [comment]
Essentially we need a way to add a (number of) turtle files with manual test case definitions using SPARQL queries to a test run.

**Comment by seebi** [comment]
Even a single turtle file would do the job :-)

**Comment by hknochi** [comment]
+1

**Comment by TheRojam** [comment]
+1

**Comment by jimkont** [comment]
I never stopped support for those :)

`org.aksw.rdfunit.model.readers.BatchTestCaseReader` can be used to read RDFUnit TestCases from a jena `Model`. which returns a collections of `TestCase` objects

The results can be wrapped in a TestSuite and validate a dataset

**Comment by jimkont** [comment]
I guess I should run by default on the input schemas if this is what you need and add these tests to the ones we get from the autogenerators
