### ISSUE TITLE
Unable to build project using docker.

### ISSUE THREAD

**Issue by AchoArnold** [AKSW/RDFUnit#95]
## Expected Behavior
Docker build should be successfull

## Actual Behavior
Docker build fails with message `E: Sub-process /usr/bin/dpkg returned an error code (1)` 

## Steps to Reproduce the Problem

  1. clone the repository
  1. run `docker build -t rdfunit .`

## Specifications

  - Version: master
  - Platform: MacOSX 10.14.5 (18F132)
  - Subsystem: Docker version 18.09.2, build 6247962

## Full Logs

https://gist.github.com/AchoArnold/f1508dc75bff86e890a492a9e3aee090

**Comment by lisa-wen** [comment]
I experienced the same behavior under Debian. Adding the following line before `apt-get install maven`:

`mkdir -p /usr/share/man/man1mkdir -p /usr/share/man/man1` 

solved it for me.

(Got it from here: https://github.com/nextcloud/docker/issues/380)

**Comment by jimkont** [comment]
Thanks, @lisa-wen I applied your suggestion to fix the issue

@AchoArnold can you confirm that this solution works

**Comment by AchoArnold** [comment]
Hello @jimkont,

I can confirm that this solves the issue. But I think you omitted `RUN` in the dockerfile. https://github.com/AKSW/RDFUnit/pull/96

**Comment by jimkont** [comment]
when you edit directly from github without testing :man_facepalming:  :)
